title Load a url and wait for load to complete

caller -> SeleniumRunner: loadAndWait
SeleniumRunner -> Browser: set page load timeout
SeleniumRunner -> Browser: set script timeout
SeleniumRunner -> Browser: Load url

note right of Browser
Wait at most "page load timeout"
milliseconds
end note

Browser -> SeleniumRunner :
SeleniumRunner -> Browser: executeScript "pageCompleteCheck"

note right of Browser
Keep testing script
at most "wait script timeout"
milliseconds
end note

Browser -> SeleniumRunner :

SeleniumRunner -> caller :