'use strict';

module.exports = {
  // Disable updates during automation
  'app.update.disabledForTesting': true,
  // Use hidden time_to_non_blank_paint
  'dom.performance.time_to_non_blank_paint.enabled': true,
  // Use hidden time to DOM Content flush
  'dom.performance.time_to_dom_content_flushed.enabled': true,
  // Use hidden TTFI
  'dom.performance.time_to_first_interactive.enabled': true,
  // Use hidden TTCP
  'dom.performance.time_to_contentful_paint.enabled': true,
  'browser.startup.homepage': 'about:blank',

  'devtools.devedition.promo.enabled': false,

  // Preferences from
  // https://searchfox.org/mozilla-central/source/testing/talos/talos/config.py
  // slightly modified - all URLs are set to blank
  'app.update.enabled': false,
  'app.update.url': '',
  'browser.aboutHomeSnippets.updateUrl': '',
  'browser.bookmarks.restore_default_bookmarks': false,
  'browser.bookmarks.added_static_root': true,
  'browser.places.importBookmarksHTML': false,
  'browser.newtabpage.directory.ping': '',
  'browser.newtabpage.directory.source': 'data:application/json,{}',
  'browser.newtabpage.enabled': false,
  'browser.newtabpage.enhanced': false,
  'browser.newtabpage.introShown': true,
  'browser.newtab.preload': false,
  'browser.pagethumbnails.capturing_disabled': true,
  'browser.rights.3.shown': true,
  'browser.search.update': false,
  'browser.sessionstore.resume_from_crash': false,
  'browser.shell.checkDefaultBrowser': false,
  'browser.startup.page': 0,
  'browser.uitour.enabled': false,
  'browser.tabs.warnOnClose': false,
  'datareporting.healthreport.service.enabled': false,
  'datareporting.healthreport.uploadEnabled': false,
  'datareporting.healthreport.service.firstRun': false,
  'datareporting.healthreport.logging.consoleEnabled': false,
  'datareporting.policy.dataSubmissionEnabled': false,
  'datareporting.policy.dataSubmissionPolicyResponseType':
    'accepted-info-bar-dismissed',
  'datareporting.policy.dataSubmissionPolicyAccepted': false,
  'dom.ipc.plugins.flash.disable-protected-mode': true,
  'dom.max_chrome_script_run_time': 0,
  'dom.max_script_run_time': 0,
  'dom.webnotifications.enabled': false,
  'extensions.checkCompatibility': false,
  'extensions.update.enabled': false,
  'extensions.update.notifyUser': false,
  'extensions.shownSelectionUI': true,
  'extensions.autoDisableScopes': 14,
  'extensions.shield-recipe-client.enabled': false,
  'extensions.systemAddon.update.url': '',
  'intl.charsetmenu.browser.cache': 'UTF-8',
  'media.gmp-gmpopenh264.autoupdate': false,
  'network.cookie.prefsMigrated': true,
  'network.proxy.type': 0,
  'pageThumbs.enabled': false,
  'pref.browser.homepage.disable_button.current_page': false,
  'privacy.cpd.siteSettings': true,
  'privacy.sanitize.migrateFx3Prefs': true,
  'privacy.sanitize.timeSpan': 0,
  'reader.parse-on-load.enabled': false,
  'security.enable_java': false,
  'security.warn_entering_weak': false,
  'security.warn_viewing_mixed': false,
  'security.warn_entering_secure': false,
  'security.warn_leaving_secure': false,
  'security.warn_submit_insecure': false,
  'services.sync.migrated': true,
  'services.sync.engine.bookmarks': false,
  'toolkit.telemetry.server': 'https://127.0.0.1/telemetry-dummy/',
  'toolkit.content-background-hang-monitor.disabled': true,
  'gfx.webrender.force-disabled': true,
  'xpinstall.whitelist.add': '',
  'xpinstall.whitelist.add.36': '',
  'xpinstall.signatures.required': false,
  'signon.rememberSignons': false,
  'javascript.options.asyncstack': false,
  'javascript.options.showInConsole': true,
  'devtools.chrome.enabled': true,
  'devtools.debugger.remote-enabled': true,
  'devtools.sourcemap.locations.enabled': false,
  'dom.push.serverURL': ''
};
