title Run one url via Engine

caller -> Engine: run
Engine -> BmpRunner: start proxy

loop n times
  Engine -> BmpRunner: createHAR OR startNewPage
  Engine -> SeleniumRunner: start
  SeleniumRunner -> Browser: launch browser
  Engine -> SeleniumRunner: loadAndWait
  SeleniumRunner -> Browser: get url and execute pageCompleteCheck
  loop for each script
    Engine -> SeleniumRunner: runScript
    SeleniumRunner -> Browser: executeScript
  end
  Engine -> SeleniumRunner: stop
  SeleniumRunner -> Browser: quit browser
  Engine -> Engine: optionally wait for short delay
end

Engine -> BmpRunner: getHAR
Engine -> BmpRunner: stop proxy

Engine -> caller : [return HAR and script results]
