#!/bin/sh

## resolve links - $0 may be a link (shell code copied from Apache Maven)
PRG="$0"
progname=`basename "$0"`

# need this for relative symlinks
while [ -h "$PRG" ] ; do
ls=`ls -ld "$PRG"`
link=`expr "$ls" : '.*-> \(.*\)$'`
if expr "$link" : '/.*' > /dev/null; then
PRG="$link"
else
PRG=`dirname "$PRG"`"/$link"
fi
done

BT_HOME=`dirname "$PRG"`/..

# make it fully qualified
BT_HOME=$(cd "$BT_HOME" > /dev/null && pwd)


MAINCLASS="net.browsertime.browsertime.run.Main"

java -classpath "${BT_HOME}/lib/*" $MAINCLASS "$@"