name: Run Docker
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the container
      run: |
        docker buildx install
        docker buildx build --load --platform linux/amd64 -t sitespeedio/browsertime .
    - name: Test Chrome
      run: docker run --rm sitespeedio/browsertime https://www.sitespeed.io -n 1 -b chrome
    - name: Test Firefox
      run: docker run --rm sitespeedio/browsertime https://www.sitespeed.io -n 1 -b firefox
    - name: Test Edge
      run: docker run --rm sitespeedio/browsertime https://www.sitespeed.io -n 1 -b edge
    - name: Test WebPageReplay
      run: docker run --cap-add=NET_ADMIN --rm  -e REPLAY=true -e LATENCY=100 sitespeedio/browsertime https://www.sitespeed.io -n 1 -b chrome 

 
        
