name: Lint
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [24.x]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Browsertime
      run: npm ci
    - name: Lint
      run: npm run lint