name: Linux browsers Firefox
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
      #with:
      #  firefox-version: '94.0'
    - name: Install Browsertime
      run: npm ci
    - name: Install dependencies
      run: |
        sudo apt-get install net-tools -y
        sudo snap install ffmpeg
        sudo snap alias ffmpeg.ffprobe ffprobe
        python -m pip install --upgrade --user pip
        python -m pip install --upgrade --user setuptools==70.0.0
        python -m pip install --user pyssim OpenCV-Python Numpy
        python -m pip --version
        python -m pip show Pillow
        python -m pip show pyssim
        python -m pip install virtualenv
        sudo modprobe ifb numifbs=1
    - name: Browser versions
      run: |
        firefox --version
    - name: Start local HTTP server
      run: (npm run start-server&)
    # - run: VTENV_OPTS="-p python3" make test
    - name: Test Firefox with throttle
      run: ./bin/browsertime.js -b firefox -n 1 http://127.0.0.1:3000/simple/ --connectivity.profile cable --connectivity.engine throttle --xvfb --firefox.collectMozLog
    - name: Test multi pages
      run: ./bin/browsertime.js -b firefox test/data/navigationscript/multi.cjs http://127.0.0.1:3000/search/ -n 1 --xvfb
    - name: Test Firefox Geckoprofiler
      run: ./bin/browsertime.js -b firefox --firefox.geckoProfiler -n 1 http://127.0.0.1:3000/simple/ --xvfb
    - name: Test Firefox with scripting
      run: ./bin/browsertime.js -b firefox test/data/commandscripts/unified.cjs --xvfb
    - name: Test Firefox with web driver nagivation
      run: ./bin/browsertime.js -b firefox -n 1 http://127.0.0.1:3000/simple/ --webdriverPageload --xvfb
    - name: Test collecting Firefox perf statistics
      run: ./bin/browsertime.js -b firefox --firefox.perfStats --xvfb http://127.0.0.1:3000/simple/
    - name: Run test with check network idle in Firefox
      run: ./bin/browsertime.js -b firefox --pageCompleteCheckNetworkIdle --xvfb http://127.0.0.1:3000/simple/
    - name: Test extra profile run Firefox
      run: ./bin/browsertime.js -b firefox http://127.0.0.1:3000/simple/ -n 1 --viewPort 1000x600 --xvfb  --enableProfileRun    
