name: Run browser test Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
      env:
        CHROMEDRIVER_SKIP_DOWNLOAD: true
        GECKODRIVER_SKIP_DOWNLOAD: true
    - run: choco install ffmpeg
    - run: choco install imagemagick.app -PackageParameters LegacySupport=true
    - run: choco install python
    - run: choco install microsoft-edge
    - run: python -m pip install --upgrade --user pip
    - run: python -m pip install --upgrade --user setuptools
    - run: python -m pip install --user pyssim
    - run: python -m pip --version
    - run: python -m pip show Pillow
    - run: python -m pip show pyssim
    - name: Run Visual Metrics test
      run: python ./browsertime/visualmetrics.py --check
      shell: cmd
    - name: Run Edge test
      run: node bin/browsertime.js -b edge -n 1 --screenshot https://www.sitespeed.io/
      shell: cmd
    - name: Run Edge test with video
      run: node bin/browsertime.js -b edge -n 1 --screenshot --video --visualMetrics https://www.sitespeed.io/
      shell: cmd
      
